
pipeline:
  name: package-booking-api
  jdkVersion: OpenJDK_11.0.2u9
  profiles:
    - DPS-AWS-EUWEST-1
    - DPS-AWS-SOUTHEAST-1
  generateDevBoard: true
  pullRequestBuilder:
    mode: SECURE
    codeAnalysis: true
  #generateRdmTicket: true
  stages:

    - name: BUILD
      jobs:
        - name: BUILD
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Build
          jenkinsAgentTags: DPS
          command: clean compile -e -U
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=BUILD

        - name: UNIT_TESTS
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Unit tests
          jenkinsAgentTags: ON_PREMISE
          command: clean test -e
          sharedArtifacts:
            - CODE_ANALYSIS:
              - '**/target/coverage-reports/jacoco-ut.exec'
              - '**/target/surefire-reports/*.xml'
          publishers:
            junit:
            - '**/target/surefire-reports/*.xml'
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=BUILD

        - name: INTEGRATION_TESTS
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Integration tests
          jenkinsAgentTags: ON_PREMISE
          command: clean integration-test -Dtest=ignoreUnitTests -DfailIfNoTests=false -Dspring.profiles.active=dpsdev,ci
          sharedArtifacts:
            - CODE_ANALYSIS:
              - '**/target/coverage-reports/jacoco-it.exec'
              - '**/target/failsafe-reports/*.xml'
              - '**/target/classes/**/*.class'
          publishers:
            junit:
            - '**/target/failsafe-reports/*.xml'
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=BUILD

        - name: CODE_ANALYSIS
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Code analysis
          jenkinsAgentTags: ON_PREMISE
          command: clean compile test -e -U sonar:sonar -Dsonar.analysis.mode=publish -Dsonar.buildbreaker.skip=false
          copyArtifactsFrom:
            - UNIT_TESTS
            - INTEGRATION_TESTS
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=BUILD

        - name: PACKAGE
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Create RPM
          jenkinsAgentTags: ON_PREMISE
          command: clean package -U -P deploy-rpm -Drpm.version=${RPM_VERSION} -Drpm.release=${RPM_RELEASE} -Dgit.commit.id=${BUILD_GIT_COMMIT} -Dmaven.test.skip=true
          sharedArtifacts:
            - UPLOAD_ARTIFACT_DEV_DPSAWS_REPO:
              - 'package-booking-api-rpm/target/rpm/package-booking-api/RPMS/noarch/package-booking-api-${RPM_VERSION}-${RPM_RELEASE}.noarch.rpm'


    - name: DEV_DPS_AWS_EUWEST_1
      jobs:
        - name: UPLOAD_ARTIFACT_DEV_DPSAWS_REPO
          type: nexus
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Upload RPM Nexus DEV
          jenkinsAgentTags: ON_PREMISE
          nexusRepositoryId: dev-dps-aws-eu-west-1-dynamic-packaging-repo
          environment: shared-hbg-aws-eu-west-1

        - name: DEPLOY_APPLICATION_DEV_DPS
          type: rundeck
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Deploy application
          jenkinsAgentTags: ON_PREMISE
          command:
            jobIdentifier: da0c5be9-df3f-4195-83b8-eccb1e64f1fb
            jobOptions:
              - environment=dev
              - region=eu-west-1
              - service_name=package-booking-api
              - version=${BUILD_VERSION}
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=DEV_DPS
              - deploy=yes

        - name: DEV_OPERATIONS_BOOKING_API
          scm:
            url: ssh://git@stash.hotelbeds:7999/qa/package-booking-api-qa.git
            branch: master
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Mini Smoke tests
          jenkinsAgentTags: ON_PREMISE
          command: -P dpsdev test -Denvironment=dpsdev -Dgroup=smoke
          publishers:
            allure:
              path: 'target/allure-results'
              version: 'allure2'
          triggerCondition: ALWAYS
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=DEV_DPS


    - name: TEST_DPS_AWS_EUWEST_1
      jobs:
        - name: RDM_APPROVAL_TEST_DPS
          type: rdm_approval
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: RDM approval
          jenkinsAgentTags: ON_PREMISE
        - name: UPLOAD_ARTIFACT_TEST_DPSAWS_REPO
          type: nexus
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Upload RPM Nexus TEST
          jenkinsAgentTags: ON_PREMISE
          nexusRepositoryId: test-dps-aws-eu-west-1-dynamic-packaging-repo
          environment: shared-hbg-aws-eu-west-1

        - name: DEPLOY_APPLICATION_TEST_DPS
          type: rundeck
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Deploy application
          jenkinsAgentTags: DPS
          command:
            jobIdentifier: da0c5be9-df3f-4195-83b8-eccb1e64f1fb
            jobOptions:
              - environment=test
              - region=eu-west-1
              - service_name=package-booking-api
              - version=${BUILD_VERSION}
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=TEST_DPS
              - deploy=yes

        - name: TEST_OPERATIONS_BOOKING_API
          scm:
            url: ssh://git@stash.hotelbeds:7999/qa/package-booking-api-qa.git
            branch: master
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Smoke tests
          jenkinsAgentTags: ON_PREMISE
          command: -P dpstest test -Denvironment=dpstest -Dgroup=smoke
          publishers:
            allure:
              path: 'target/allure-results'
              version: 'allure2'
          triggerCondition: ALWAYS
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=TEST_DPS

    - name: LIVE_DPS_AWS_EUWEST_1
      jobs:
        - name: RDM_APPROVAL_LIVE_DPS
          type: rdm_approval
          profiles: DPS-AWS-EUWEST-1
          showName: RDM approval
          jenkinsAgentTags: ON_PREMISE

        - name: UPLOAD_ARTIFACT_LIVE_DPSAWS_REPO
          type: nexus
          profiles: DPS-AWS-EUWEST-1
          showName: Upload RPM Nexus LIVE
          jenkinsAgentTags: ON_PREMISE
          nexusRepositoryId: live-dps-aws-eu-west-1-dynamic-packaging-repo
          environment: shared-hbg-aws-eu-west-1

        - name: DEPLOY_APPLICATION_LIVE_DPS
          type: rundeck
          profiles: DPS-AWS-EUWEST-1
          showName: Deploy application
          jenkinsAgentTags: ON_PREMISE
          command:
            jobIdentifier: ae289658-f1c1-441f-a17e-ea3904ee41ce
            jobOptions:
              - environment=live
              - region=eu-west-1
              - service_name=package-booking-api
              - version=${BUILD_VERSION}
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=LIVE_DPS
              - deploy=yes

        - name: TAG
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
          showName: Git tagging
          jenkinsAgentTags: ON_PREMISE
          command: org.honton.chas:git-tag-maven-plugin:tag -Dgit.tagName=${BUILD_VERSION} -Dgit.use.ssh=true -DskipTests
          triggerCondition: ALWAYS
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=LIVE_DPS

    - name: LIVE_DPS_AWS_SOUTHEAST_1
      jobs:
        - name: RDM_APP_LIVE_DPS_SOUTHEAST
          type: rdm_approval
          profiles: DPS-AWS-SOUTHEAST-1
          showName: RDM approval Asia
          jenkinsAgentTags: ON_PREMISE

        - name: DEPLOY_APP_DEV_DPS_SOUTHEAST
          type: rundeck
          profiles: DPS-AWS-SOUTHEAST-1
          showName: Deploy application Asia
          jenkinsAgentTags: ON_PREMISE
          command:
            jobIdentifier: aa8abe43-943c-4aa4-b8f5-913cf2757466
            jobOptions:
            - environment=dev
            - version=${BUILD_VERSION}
            - region=ap-southeast-1
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=DEV_DPS
              - deploy=yes
