
pipeline:
  name: package-booking-api
  jdkVersion: OpenJDK_11.0.2u9
  profiles:
    - DPS-AWS-EUWEST-1
    - DPS-AWS-SOUTHEAST-1
  generateDevBoard: true
  pullRequestBuilder:
    mode: SECURE
    codeAnalysis: true
  #generateRdmTicket: true
  stages:

    - name: BUILD
      jobs:
        - name: BUILD
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Build
          jenkinsAgentTags: DPS
          command: clean compile -e -U
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=BUILD

        - name: UNIT_TESTS
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Unit tests
          jenkinsAgentTags: ON_PREMISE
          command: clean test -e
          sharedArtifacts:
            - CODE_ANALYSIS:
              - '**/target/coverage-reports/jacoco-ut.exec'
              - '**/target/surefire-reports/*.xml'
          publishers:
            junit:
            - '**/target/surefire-reports/*.xml'
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=BUILD

        - name: INTEGRATION_TESTS
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Integration tests
          jenkinsAgentTags: ON_PREMISE
          command: clean integration-test -Dtest=ignoreUnitTests -DfailIfNoTests=false -Dspring.profiles.active=dpsdev,ci
          sharedArtifacts:
            - CODE_ANALYSIS:
              - '**/target/coverage-reports/jacoco-it.exec'
              - '**/target/failsafe-reports/*.xml'
              - '**/target/classes/**/*.class'
          publishers:
            junit:
            - '**/target/failsafe-reports/*.xml'
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=BUILD

        - name: CODE_ANALYSIS
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Code analysis
          jenkinsAgentTags: ON_PREMISE
          command: clean compile test -e -U sonar:sonar -Dsonar.analysis.mode=publish -Dsonar.buildbreaker.skip=false
          copyArtifactsFrom:
            - UNIT_TESTS
            - INTEGRATION_TESTS
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=BUILD

        - name: PACKAGE
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Create RPM
          jenkinsAgentTags: ON_PREMISE
          command: clean package -U -P deploy-rpm -Drpm.version=${RPM_VERSION} -Drpm.release=${RPM_RELEASE} -Dgit.commit.id=${BUILD_GIT_COMMIT} -Dmaven.test.skip=true
          sharedArtifacts:
            - UPLOAD_ARTIFACT_DEV_DPSAWS_REPO:
              - 'package-booking-api-rpm/target/rpm/package-booking-api/RPMS/noarch/package-booking-api-${RPM_VERSION}-${RPM_RELEASE}.noarch.rpm'


    - name: DEV_DPS_AWS_EUWEST_1
      jobs:
        - name: BUILD
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Build
          jenkinsAgentTags: DPS
          command: clean compile -e -U
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=BUILD


    - name: TEST_DPS_AWS_EUWEST_1
      jobs:
        - name: BUILD
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Build
          jenkinsAgentTags: DPS
          command: clean compile -e -U
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=BUILD


    - name: LIVE_DPS_AWS_EUWEST_1
      jobs:
        - name: BUILD
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Build
          jenkinsAgentTags: DPS
          command: clean compile -e -U
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=BUILD

    - name: LIVE_DPS_AWS_SOUTHEAST_1
      jobs:
        - name: BUILD
          type: maven
          profiles:
            - DPS-AWS-EUWEST-1
            - DPS-AWS-SOUTHEAST-1
          showName: Build
          jenkinsAgentTags: DPS
          command: clean compile -e -U
          datadog:
            tags:
              - pipeline=package-booking-api
              - stage=BUILD
