
pipeline:
  name: jenkinstest
  repo: git://github.com/gpuigros/jenkinstest.git
  stages:
    - name: BUILD
      jobs:
        - name: BUILD
          type: maven
          showName: Build
          jenkinsAgentTags: DPS
          command: clean compile -e -U

